services:
  - type: web
    name: luxe-web
    env: python
    plan: free
    runtime: python-3.12.12

    buildCommand: |
      pip install --upgrade pip setuptools wheel
      pip install -r requirements.txt
      python manage.py collectstatic --noinput

    startCommand: python -m gunicorn LUXEBIJOUX.wsgi --chdir LUXEBIJOUX --bind 0.0.0.0:$PORT --log-file -

    envVars:
      - key: SECRET_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: ALLOWED_HOSTS
        sync: false